
server:
  port: 9089
spring:
  application:
    name: task-management
  datasource:
    url: jdbc:mysql://localhost:3306/task-management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 985263
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true